CREATE TABLE loan (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, book_id INT DEFAULT NULL, loaned_at DATETIME NOT NULL, returned_at DATETIME DEFAULT NULL, INDEX IDX_C5D30D03A76ED395 (user_id), INDEX IDX_C5D30D0316A2B381 (book_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE loan ADD CONSTRAINT FK_C5D30D03A76ED395 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE loan ADD CONSTRAINT FK_C5D30D0316A2B381 FOREIGN KEY (book_id) REFERENCES books (id);
